### PR TITLE
updates redirect handling and fix httpResponseCode

### LINKED ISSUE #29: Allow redirect to page AND language in v10
It is possible to set a target page uid and a target sys_language in typoscript settings.

But in `locate/Classes/Action/Redirect.php->redirectToPid()` only one of them is executed.

### LINKED ISSUE #30: httpResponseCode is not used in v10
In typoscript it is possible to set a "httpResponseCode"

This is saved to `$config['settings']['responseCode']` here:
https://github.com/Leuchtfeuer/locate/blob/dev-10.0/Classes/Middleware/LanguageRedirectMiddleware.php#L54

But the `locate/Classes/Action/Redirect.php->process()`  checks for the original name and casts it to (int) although it should be a string like "HTTP/1.1 301 Moved Permanently"

`$this->httpStatus = $this->configuration['httpResponseCode'] ? (int)$this->configuration['httpResponseCode'] : HttpUtility::HTTP_STATUS_301;`

### PR DESCRIPTION
**Pull request by tgriessbach**
Resolves #29 
Resolves #30

### CODE REVIEW

**Comment by elbebass** [comment]
First of all thanks for the effort @tgriessbach. We will review the PR and release a new version via Packagist.org soon.

**Review by davkraid — APPROVED** [review]
LGTM

**Comment by tgriessbach** [comment]
Hi everyone, thanks for checking and approving th PR.
Any idea when you can add it to a new release?

**Review by balasch — APPROVED** [review]
👍

**Pull request merged**
